help:
  - '&6-----------------------------------------------------'
  - '&3/ignore <name> to ignore a player.'
  - '&3/ignorelist to list ignored players.'
  - '&3/r <message> to reply to the last person that messaged you.'
  - '&3/l <message> to message the last person that you messaged.'
  - '&3/w <name> <message> OR /msg <name> <message> to pm a player.'
  - '&3/vote to vote'
  - '&3/kill to kill yourself.'
  - '&6-----------------------------------------------------'